# docker-compose.yml
version: '3.8'

services:
  meta-grpc-server:
    image: mokusei/meta-integration:latest
    container_name: meta-grpc-server
    ports:
      - "50051:50051"
    restart: unless-stopped
    env_file:
      - .env
