version: '3.8'

services:
  meta-grpc-server:
    image: ghcr.io/israelviana/handler-user-message:latest
    pull_policy: always
    container_name: meta-server
    restart: unless-stopped
    ports:
      - "50051:50051"
    environment:
      BASE_URL_META: ${BASE_URL_META}
      ACCESS_TOKEN_META: ${ACCESS_TOKEN_META}
      BACKUP_ACCESS_TOKEN_META: ${BACKUP_ACCESS_TOKEN_META}
      FROM_NUMBER_ID_META: ${FROM_NUMBER_ID_META}
      WHATSAPP_BUSINESS_ACCOUNT_ID_META: ${WHATSAPP_BUSINESS_ACCOUNT_ID_META}
      META_VERIFY_TOKEN: ${META_VERIFY_TOKEN}
    networks:
      - tito-network

networks:
  tito-network:
    driver: bridge